version: '2.8'

services:
  kafka-cluster:
    image: landoop/fast-data-dev:latest
    environment:
      ADV_HOST: kafka-cluster
      RUNTESTS: 0                
    ports:
      - 2181:2181                 
      - 3030:3030              
      - 8081-8083:8081-8083       
      - 9581-9585:9581-9585    
      - 9092:9092
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://kafka-cluster:8081/subjects/nyc_yellow_taxi_trip_data-value/versions/latest" ]
      interval: 30s
      timeout: 10s
      retries: 10

  kafka-create-resources:
    image: custom-kafka-resource-creator
    depends_on:
      kafka-cluster:
        condition: service_healthy
    environment:
      SCHEMA_REGISTRY_URL: http://kafka-cluster:8081

  kafka-create-topics:
    image: landoop/fast-data-dev:latest
    depends_on:
      kafka-cluster:
        condition: service_healthy
    command: > 
        sh -c "kafka-topics --create --bootstrap-server kafka-cluster:9092 --topic producer.to.processor --replication-factor 1 --partitions 3 &&
               kafka-topics --create --bootstrap-server kafka-cluster:9092 --topic processor.to.marketing --replication-factor 1 --partitions 3 &&
               kafka-topics --create --bootstrap-server kafka-cluster:9092 --topic processor.to.finance --replication-factor 1 --partitions 3 &&
               kafka-topics --create --bootstrap-server kafka-cluster:9092 --topic processor.to.logistics --replication-factor 1 --partitions 3"

  event-processor-1:
      depends_on:
        kafka-cluster:
          condition: service_healthy
      image: custom-producer
      command: >
        sh -c "echo Sleeping for a while to wait for resource creation, look at the docs about this sleep :sad: &&
               sleep 45 && 
               python ./event_processor/main.py -log_level DEBUG -processor_id event-processor-1 -bootstrap_server kafka-cluster:9092 -schema_registry_url http://kafka-cluster:8081 -source_topic producer.to.processor -batch_size_to_commit_offsets 20 -destination_configurations '{\"FINANCE\": {\"output_topic\": \"processor.to.finance\", \"output_subject\": \"processor.to.consumer-value\"}, \"MARKETING\": {\"output_topic\": \"processor.to.marketing\", \"output_subject\": \"processor.to.consumer-value\"}, \"LOGISTICS\": {\"output_topic\": \"processor.to.logistics\", \"output_subject\": \"processor.to.consumer-value\"}}' -group_id event_processor"

  producer-1:
    depends_on:
      kafka-cluster:
        condition: service_healthy
    image: custom-producer
    command: >
      sh -c "echo Sleeping for a while to wait for resource creation, look at the docs about this sleep :sad: &&
             sleep 60 && 
             python ./dummy_producer/main.py -log_level DEBUG -bootstrap_server kafka-cluster:9092 -schema_registry_url http://kafka-cluster:8081 -target_topic producer.to.processor -origin_service_type FINANCE -origin_service_id producer-1 -list_of_destinations MARKETING LOGISTICS -amount_of_messages 2002 -sleep_between_messages_in_seconds 1"

  producer-2:
    depends_on:
      kafka-cluster:
        condition: service_healthy
    image: custom-producer
    command: >
      sh -c "echo Sleeping for a while to wait for resource creation, look at the docs about this sleep :sad: &&
             sleep 60 && 
             python ./dummy_producer/main.py -log_level DEBUG -bootstrap_server kafka-cluster:9092 -schema_registry_url http://kafka-cluster:8081 -target_topic producer.to.processor -origin_service_type AUDITING -origin_service_id producer-2 -list_of_destinations FINANCE LOGISTICS -amount_of_messages 2002 -sleep_between_messages_in_seconds 1"

