# See: https://github.com/cloudhut/kowl/tree/master/docs/config for reference config files.
kafka:
  brokers:
    - kafka-cluster:9092
  schemaRegistry:
    enabled: true
    urls: ["http://kafka-cluster:8081"]

connect:
  enabled: true
  clusters:
    - name: connect
      url: http://kafka-cluster:8083

# server:
  # listenPort: 8080