# See: https://github.com/cloudhut/kowl/tree/master/docs/config for reference config files.
kafka:
  brokers:
    - redpanda:29092
  schemaRegistry:
    enabled: true
    urls: ["http://redpanda:8081"]

connect:
  enabled: false
  clusters:
    - name: connect
      url: http://connect:8083

# server:
  # listenPort: 8080